# Список категорий
GET http://localhost:3000/api/categories HTTP/1.1

###

# Поиск
GET http://localhost:3000/api/search?query=достигнуть HTTP/1.1

###

# Список постов
GET http://localhost:3000/api/articles HTTP/1.1

###

# Пост
GET http://localhost:3000/api/articles/ic8jsr HTTP/1.1

###

# Создание нового поста
POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "title": "Новый заголовок",
  "category": [
    "Новая категория"
  ],
  "date": "23-02-2021",
  "announce": "Новый анонс"
}

###

# Обновление поста
PUT http://localhost:3000/api/articles/ic8jsr HTTP/1.1
Content-Type: application/json

{
  "title": "Обновленный заголовок 22",
  "category": [
    "Кино"
  ],
  "date": "23-02-2021",
  "announce": "Анонс"
}

###

# Удаление поста
DELETE http://localhost:3000/api/articles/GWc2ik HTTP/1.1

###

# Получение комментариев поста
GET http://localhost:3000/api/articles/GWc2ik/comments HTTP/1.1

###

# Удаление комментариев поста
DELETE http://localhost:3000/api/articles/ic8jsr/comments/nZSe_fs HTTP/1.1

###

# Добавление нового комментария
POST http://localhost:3000/api/articles/ic8jsr/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Тест добавления комментария"
}
